name: (main) [backend] Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'database/**'
      - '.github/workflows/backend-main.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Update wrangler config with environment variables
        run: |
          jq_filter='.d1_databases[0].database_id = $dbid0
          | .d1_databases[0].database_name = $dbname0
          | .d1_databases[1].database_id = $dbid1
          | .d1_databases[1].database_name = $dbname1
          | .account_id = $accountId'

          jq \
            --arg dbid0 "${{ vars.TELEGRAM_MESSAGES_DB_ID }}" \
            --arg dbname0 "${{ vars.TELEGRAM_MESSAGES_DB_NAME }}" \
            --arg dbid1 "${{ vars.MAIN_DB_ID }}" \
            --arg dbname1 "${{ vars.MAIN_DB_NAME }}" \
            --arg accountId "${{ vars.CLOUDFLARE_ACCOUNT_ID }}" \
            "$jq_filter" \
            wrangler.jsonc > wrangler.local.jsonc

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy --config wrangler.local.jsonc --name ${{ vars.THIS_APP_NAME_BE }}

      - name: Set secrets in Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | wrangler secret put TELEGRAM_BOT_TOKEN --config wrangler.local.jsonc --name ${{ vars.THIS_APP_NAME_BE }}
          echo "${{ secrets.TELEGRAM_WEBHOOK_SECRET }}" | wrangler secret put TELEGRAM_WEBHOOK_SECRET --config wrangler.local.jsonc --name ${{ vars.THIS_APP_NAME_BE }}
          echo "${{ secrets.ADMIN_SECRET }}" | wrangler secret put ADMIN_SECRET --config wrangler.local.jsonc --name ${{ vars.THIS_APP_NAME_BE }}

      - name: Migrate D1 Databases
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler d1 migrations apply ${{ vars.TELEGRAM_MESSAGES_DB_NAME }} --remote --config wrangler.local.jsonc
          wrangler d1 migrations apply ${{ vars.MAIN_DB_NAME }} --remote --config wrangler.local.jsonc
